# Generated by Django 4.2.10 on 2024-02-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badpeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('feature', models.JSONField(blank=True, null=True, unique=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=30)),
                ('image', models.ImageField(upload_to='badpeople/')),
            ],
        ),
    ]
